project:
  type: book
  output-dir: docs

book:
  title: "BURCU ALTIPARMAK Progress Journal"
  repo-url: https://github.com/pjournal/mef07-BurcuAltiparmak
  chapters:
    - index.qmd
    - assignment1.qmd
    - inClass1.qmd
    - inClass2.qmd
    
  page-footer: 
    center: "[MEF BDA 503](https://mef-bda503.github.io)" 
  sharing: [twitter, facebook]

format:
  html:
    theme: cosmo


